Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -47,14 +47,14 @@ deploy:
         ssh root@$IP << 'EOF'
           # Kiểm tra nginx có tồn tại hay không
           if ! command -v nginx &> /dev/null; then
-            echo "[Error] Nginx is not installed!"
-            exit 1
+                echo "[Error] Nginx is not installed!"
+                exit 1
           fi
 
           # Kiểm tra thư mục /etc/nginx/modsec có tồn tại hay không
           if [ ! -d "/etc/nginx/modsec" ]; then
-            echo "[Error] Folder /etc/nginx/modsec not exist!"
-            exit 1
+                echo "[Error] Folder /etc/nginx/modsec not exist!"
+                exit 1
           fi
 
           # Copy /etc/nginx/modsec vào /tmp/waf-manager/modsec để backup
@@ -63,20 +63,21 @@ deploy:
           # Di chuyển local-conf vào /etc/nginx/modsec
           mv /tmp/waf-manager/local-conf /etc/nginx/modsec/
         EOF
-        
-         # SSH vào IP để kiểm tra nginx config và xử lý theo kết quả
+
+        # SSH vào IP để kiểm tra nginx config và xử lý theo kết quả
         ssh root@$IP << 'EOF'
           # Kiểm tra cấu hình nginx
           if nginx -t; then
             # Nếu cấu hình hợp lệ, reload nginx
             nginx -s reload
             echo "[OK] Nginx reloaded successfully on $IP"
-            return 0
+            exit 0
           else
             # Nếu cấu hình không hợp lệ, khôi phục lại modsec từ bản backup
             echo "[Error] Restoring previous modsec configuration..."
             cp -r /tmp/waf-manager/modsec /etc/nginx/modsec
-            return 1
+            exit 1
           fi
         EOF
       done
+
