update cd

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -33,34 +33,50 @@ deploy:
   script:
     # Copy the configuration to the NGINX server
     - |
+      # Lặp qua từng IP trong biến NGINX_IPS
       for IP in $NGINX_IPS; do
-        echo "Deploying to NGINX server at $IP...";
+        echo "Deploying on $IP"
 
-        # Check if NGINX is installed and if /etc/nginx/modsec exists on the server
-        ssh root@$IP '
+        # Tạo thư mục /tmp/waf-manager trên server từ xa
+        ssh root@$IP "mkdir -p /tmp/waf-manager/"
+
+        # Copy thư mục local-conf đến /tmp/waf-manager/
+        scp -r local-conf root@$IP:/tmp/waf-manager/
+
+        # SSH vào IP để thực hiện các lệnh kiểm tra ban đầu và copy config
+        ssh root@$IP << 'EOF'
+          # Kiểm tra nginx có tồn tại hay không
           if ! command -v nginx &> /dev/null; then
-              echo "NGINX is not installed on server $IP. Exiting with failure."
-              exit 1
+            echo "[Error] Nginx is not installed!"
+            exit 1
           fi
 
-          if [ -d "/etc/nginx/modsec" ]; then
-              echo "Directory exists on server $IP. Copying local-conf to /etc/nginx/modsec...";
-              scp -r local-conf/* root@$IP:/etc/nginx/modsec
+          # Kiểm tra thư mục /etc/nginx/modsec có tồn tại hay không
+          if [ ! -d "/etc/nginx/modsec" ]; then
+            echo "[Error] Folder /etc/nginx/modsec not exist!"
+            exit 1
+          fi
+
+          # Copy /etc/nginx/modsec vào /tmp/waf-manager/modsec để backup
+          cp -r /etc/nginx/modsec /tmp/waf-manager/modsec
+
+          # Di chuyển local-conf vào /etc/nginx/modsec
+          mv /tmp/waf-manager/local-conf /etc/nginx/modsec/
+        EOF
+        
+         # SSH vào IP để kiểm tra nginx config và xử lý theo kết quả
+        ssh root@$IP << 'EOF'
+          # Kiểm tra cấu hình nginx
+          if nginx -t; then
+            # Nếu cấu hình hợp lệ, reload nginx
+            nginx -s reload
+            echo "[OK] Nginx reloaded successfully on $IP"
+            return 0
           else
-              echo "Directory /etc/nginx/modsec does not exist on server $IP. Exiting with failure."
-              exit 1
+            # Nếu cấu hình không hợp lệ, khôi phục lại modsec từ bản backup
+            echo "[Error] Restoring previous modsec configuration..."
+            cp -r /tmp/waf-manager/modsec /etc/nginx/modsec
+            return 1
           fi
-
-          # Test NGINX configuration
-          echo "Testing NGINX configuration on server $IP...";
-          if ! nginx -t; then
-              echo "NGINX configuration test failed on server $IP. Exiting with failure."
-              exit 1
-          fi
-        '
-
-        # Reload NGINX if configuration is valid
-        echo "Reloading NGINX on server $IP...";
-        ssh root@$IP 'nginx -s reload'
-
-      done
+        EOF
+      done 
